### ISSUE TITLE
[process exited with code 3758096423 (0xe0000027)]

### ISSUE THREAD

**Issue by thetechgy** [Trimarc/invoke-TrimarcADChecks#6]
I'm running the script on a Server 2022 instance which is not a domain controller. I'm running it as a standard domain user. I get the output below - is this expected? I get 23 files generated before running into this

```
SYSVOL Scan for Group Policy Preference Passwords:

[process exited with code 3758096423 (0xe0000027)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by thetechgy** [comment]
The issue appears to be encountered when running `Get-SYSVOLcpassword` - for some reason when running it in VS Code, the PS extension crashes. The subsequent functions work as expected, so this appears to be the issue

**Comment by thetechgy** [comment]
```
[Warn  - 2:51:11 PM] OmniSharp.Extensions.LanguageServer.Server.Configuration.DidChangeConfigurationProvider: No ConfigurationItems have been defined, configuration won't surface any configuration from the client! | 
[Warn  - 2:51:17 PM] Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost: Runtime exception occurred while executing command:

System.Management.Automation.IncompleteParseException: The string is missing the terminator: '.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, PSInvocationSettings settings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Utility.PowerShellExtensions.InvokeAndClear[TResult](PowerShell pwsh, PSInvocationSettings invocationSettings)
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.ExecuteNormally(CancellationToken cancellationToken) | 
[Error - 2:53:15 PM] Microsoft.PowerShell.EditorServices.Services.PowerShell.Host.PsesInternalHost: Null reference exception from PowerShell.Stop received. - System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.PowerShell.Stop()
   at Microsoft.PowerShell.EditorServices.Services.PowerShell.Execution.SynchronousPowerShellTask`1.CancelNormalExecution() | 
[Error - 2:55:39 PM] Connection to PowerShell Editor Services (the Extension Terminal) was closed. See below prompt to restart!
```

**Comment by thetechgy** [comment]
This appears to have been a result of Crowdstrike Falcon blocking the findstr activity that this function was performing
